name: Docker Build Image

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image from Dockerfile
        run: |
          docker build -t backend .

      - name: Run Trivvy vilnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'backend'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
